version: '3.9'

volumes:
  postgres_data:

services:
  db:
    image: postgres:15
    env_file: 
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
     - "5432:5432"

  web:
    build: .
    restart: always
    command: >
      sh -c "cd doc_manager &&
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

