# Generated by Django 5.2.1 on 2025-06-01 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование заказчика')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование объекта')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('doc_type', models.IntegerField(choices=[(1, 'КЖ'), (2, 'КМ'), (3, 'АР')], verbose_name='Вид документации')),
                ('volume', models.FloatField(verbose_name='Объем')),
                ('filename', models.CharField(max_length=256, verbose_name='Название файла')),
                ('invenroty_number', models.CharField(max_length=50, verbose_name='Инвентарный номер')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Заказчик')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.object', verbose_name='объект')),
            ],
        ),
    ]
