# Generated by Django 5.2.1 on 2025-06-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_invenroty_number_album_inventory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='inventory_number',
            field=models.CharField(max_length=50, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='album',
            name='volume',
            field=models.FloatField(null=True, verbose_name='Объем'),
        ),
    ]
