# Generated by Django 5.2.1 on 2025-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_album_inventory_number_alter_album_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='doc_type',
            field=models.IntegerField(choices=[(1, 'КЖ'), (2, 'КМ'), (3, 'АР')], null=True, verbose_name='Вид документации'),
        ),
        migrations.AlterField(
            model_name='album',
            name='filename',
            field=models.CharField(max_length=256, null=True, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='album',
            name='inventory_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='Наименование'),
        ),
    ]
